apiVersion: v1
kind: ConfigMap
metadata:
  name: omero-autotagger-config
data:
  patch.py: |
    from omero.gateway import RoiWrapper, ImageWrapper
    def getRois(self):
        """
    Gathers OMERO RoiI objects.

    Parameters
    ----------
    self: omero.gateway.ImageWrapper
        Omero Image object from conn.getObjects()
    roi_service: omero.RoiService, optional
        Allows roiservice passthrough for performance
        """
        roi_service = self._conn.getRoiService()

        result = roi_service.findByImage(self.getId(), None, self._conn.SERVICE_OPTS)
        rv = []
        if result.rois:
            for roi in result.rois:
                rv.append(RoiWrapper(self._conn, roi))
        
        roi_service.close()
        return rv

    if not hasattr(ImageWrapper, 'getROIs'):
        ImageWrapper.getRois = getRois


  tag_rules.yml: |
    - capture: "([^_.]+)"
      blacklist:
        - Large
        - Deeper
        - Deeper2
        - Deeper3
        - Deeper4
        - 2
        - 3
        - 4
    
    - name: Annotate
      rules:
        - attribute_path: ["image", "roicount"]
          operation: lt
          value: 1
    - name: Finished
      rules:
        - attribute_path: ["image", "roicount"]
          operation: gt
          value: 0
    
    - name: "Transferred_ROIs"
      rules:
        - attribute_path: ["image", "roi", "shape", "textvalue"]
          operation: eq
          value: "Transferred Annotation"
    
    - name: PROSTATE
      rules:
        - attribute_path: ["image", "parent", "parent"]
          operation: eq
          value: "PROSTATE"
    - name: "Benign_Atrophy"
      rules:
        - attribute_path: ["image", "roi", "shape", "strokecolor"]
          operation: eq
          value: 255
    - name: "Seminal_Vesicles"
      rules:
        - attribute_path: ["image", "roi", "shape", "strokecolor"]
          operation: eq
          value: 420806655
    - name: "HGPIN"
      rules:
        - attribute_path: ["image", "roi", "shape", "strokecolor"]
          operation: eq
          value: -8781569
    - name: "Corpora"
      rules:
        - attribute_path: ["image", "roi", "shape", "strokecolor"]
          operation: eq
          value: -15728385
    - name: "Grade_3"
      rules:
        - attribute_path: ["image", "roi", "shape", "strokecolor"]
          operation: eq
          value: 822031103
    - name: "Grade_4_FG"
      rules:
        - attribute_path: ["image", "roi", "shape", "strokecolor"]
          operation: eq
          value: -387841
    - name: "Grade_4_CG"
      rules:
        - attribute_path: ["image", "roi", "shape", "strokecolor"]
          operation: eq
          value: -32047105
    - name: "Grade_5"
      rules:
        - attribute_path: ["image", "roi", "shape", "strokecolor"]
          operation: eq
          value: 570425343
    - name: "Vessel"
      rules:
        - attribute_path: ["image", "roi", "shape", "strokecolor"]
          operation: eq
          value: -1245970945
